[versions]
agp = "8.13.0"
kotlin = "2.2.10"
# https://github.com/google/ksp/releases
ksp = "2.2.10-2.0.2"

composeMultiplatform = "1.8.2"
aboutlibraries = "12.2.4"
kotlinx-serialization = "1.9.0"

android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-splashscreen = "1.0.1"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.3"
androidx-navigation = "2.9.0-rc01"
androidx-browser = "1.9.0"
androidxGlance = "1.1.1"
material = "1.13.0"
material-icons = "1.7.3"
ktorfit = "2.6.4"
ktor = "3.2.3"
koin-bom = "4.1.1"
coil-bom = "3.3.0"
kermit = "2.0.8"
cmptoast = "1.0.7"
filekit = "0.10.0"
mmkv = "2.2.3"
room = "2.7.2"
kotlin-crypto-hash = "0.7.1"
cryptography = "0.5.0"
compose-preference = "2.1.0"
ios-settings = "1.3.0"
work-runtime-ktx = "2.10.3"
paging = "3.3.0-alpha02-0.5.1"
sheets-compose-dialogs = "2.0.0-alpha03"
zoomimage = "1.4.0"
krop = "0.2.0"
accompanist = "0.37.3"
apache-compress = "1.28.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidxGlance" }
androidx-glance-widget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidxGlance" }

material = { module = "com.google.android.material:material", version.ref = "material" }

material-icon = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
material-icon-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib-light", version.ref = "ktorfit" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
koin-android = { module = "io.insert-koin:koin-android" }

coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil-bom" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3" }
coil-cache-control = { module = "io.coil-kt.coil3:coil-network-cache-control" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }

cmptoast = { module = "network.chaintech:cmptoast", version.ref = "cmptoast" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

mmkv-android = { module = "com.tencent:mmkv", version.ref = "mmkv" }

aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose-core", version.ref = "aboutlibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }

androidx-room = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

kotlin-crypto-hash-bom = { group = "org.kotlincrypto.hash", name = "bom", version.ref = "kotlin-crypto-hash" }
kotlin-crypto-hash-md = { group = "org.kotlincrypto.hash", name = "md" }
kotlin-crypto-hash-sha1 = { group = "org.kotlincrypto.hash", name = "sha1" }
kotlin-crypto-hash-sha2 = { group = "org.kotlincrypto.hash", name = "sha2" }

cryptography-bom = { group = "dev.whyoleg.cryptography", name = "cryptography-bom", version.ref = "cryptography" }
cryptography-core = { group = "dev.whyoleg.cryptography", name = "cryptography-core" }
cryptography-provider-optimal = { group = "dev.whyoleg.cryptography", name = "cryptography-provider-optimal" }

compose-preference = { group = "me.zhanghai.compose.preference", name = "preference", version.ref = "compose-preference" }

ios-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "ios-settings" }

paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "paging" }

sheets-compose-dialogs = { group = "vip.mystery0.sheets-compose-dialogs", name = "core", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-calendar = { group = "vip.mystery0.sheets-compose-dialogs", name = "calendar", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-color = { group = "vip.mystery0.sheets-compose-dialogs", name = "color", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-clock = { group = "vip.mystery0.sheets-compose-dialogs", name = "clock", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-datetime = { group = "vip.mystery0.sheets-compose-dialogs", name = "date-time", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-info = { group = "vip.mystery0.sheets-compose-dialogs", name = "info", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-input = { group = "vip.mystery0.sheets-compose-dialogs", name = "input", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-list = { group = "vip.mystery0.sheets-compose-dialogs", name = "list", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-option = { group = "vip.mystery0.sheets-compose-dialogs", name = "option", version.ref = "sheets-compose-dialogs" }
sheets-compose-dialogs-state = { group = "vip.mystery0.sheets-compose-dialogs", name = "state", version.ref = "sheets-compose-dialogs" }

zoomimage = { group = "io.github.panpf.zoomimage", name = "zoomimage-compose-coil3", version.ref = "zoomimage" }

krop = { group = "com.attafitamim.krop", name = "ui", version.ref = "krop" }
krop-filekit = { group = "com.attafitamim.krop", name = "extensions-filekit", version.ref = "krop" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

apache-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "apache-compress" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialize = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
room = { id = "androidx.room", version.ref = "room" }