[versions]
agp = "8.9.0"
kotlin = "2.1.10"
# https://github.com/google/ksp/releases
ksp = "2.1.10-1.0.31"
aboutlibraries = "11.6.3"

composeBom = "2025.03.00"
material = "1.12.0"
androidxCore = "1.15.0"
androidxCompose = "1.10.1"
androidxLifecycle = "2.8.7"
androidxCompat = "1.7.0"
androidxAnimation = "1.7.8"
androidxSplashScreen = "1.0.1"
androidxBrowser = "1.8.0"
androidxFuture = "1.2.0"
androidxGlance = "1.1.1"
androidxPaging = "3.3.6"
androidxRoom = "2.6.1"
androidxWorkManager = "2.10.0"

aboutlibrariesDependencies = "11.6.3"
accompanist = "0.37.2"
sheetsComposeDdialogs = "1.3.0"
lottie = "6.6.3"
koin = "4.0.2"
coil = "2.7.0"
retrofit = "2.11.0"
moshi = "1.15.2"
mmkv = "2.1.0"
composePreference = "1.1.1"
ucrop = "2.2.9"
featurehub = "2.2"
jpush = "5.5.4"
hmsPush = "6.12.0.300"
zoomimage = "1.1.2"

[libraries]
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
agcp = { group = "com.huawei.agconnect", name = "agcp", version = "1.9.1.301" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-material-icon = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-material-icon-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxCompat" }
androidx-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidxAnimation" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "androidxFuture" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidxGlance" }
androidx-glance-widget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidxGlance" }
androidx-paging3 = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "androidxPaging" }
androidx-paging3-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-workmanager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkManager" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

sheets-compose-dialogs = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "core", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-calendar = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "calendar", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-color = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "color", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-clock = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "clock", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-datetime = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "date-time", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-info = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "info", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-input = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "input", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-list = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "list", version.ref = "sheetsComposeDdialogs" }
sheets-compose-dialogs-option = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "option", version.ref = "sheetsComposeDdialogs" }

lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

mmkv = { group = "com.tencent", name = "mmkv-static", version.ref = "mmkv" }

compose-preference = { group = "me.zhanghai.compose.preference", name = "library", version.ref = "composePreference" }

ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "ucrop" }

feature-hub = { group = "io.featurehub.sdk", name = "java-client-android", version.ref = "featurehub" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.18.3" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version = "2.18.3" }

jpush-google = { group = "cn.jiguang.sdk", name = "jpush-google", version.ref = "jpush" }
jpush-plugin-huawei = { group = "cn.jiguang.sdk.plugin", name = "huawei", version.ref = "jpush" }
hms-push = { group = "com.huawei.hms", name = "push", version.ref = "hmsPush" }

aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibrariesDependencies" }
aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlibrariesDependencies" }

zoomimage = { group = "io.github.panpf.zoomimage", name = "zoomimage-compose-coil2", version.ref = "zoomimage" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
huawei-ag-connect = { id = "com.huawei.agconnect" }
